package com.acme.simple_kjar;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class P implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean p;

	private java.lang.Boolean b;

	private java.lang.Boolean a;

	public P() {
	}

	public java.lang.Boolean getP() {
		return this.p;
	}

	public void setP(java.lang.Boolean p) {
		this.p = p;
	}

	public java.lang.Boolean getB() {
		return this.b;
	}

	public void setB(java.lang.Boolean b) {
		this.b = b;
	}

	public java.lang.Boolean getA() {
		return this.a;
	}

	public void setA(java.lang.Boolean a) {
		this.a = a;
	}

	public P(java.lang.Boolean p, java.lang.Boolean b, java.lang.Boolean a) {
		this.p = p;
		this.b = b;
		this.a = a;
	}

}