package com.acme.simple_kjar;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class P implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean p;

	public P() {
	}

	public java.lang.Boolean getP() {
		return this.p;
	}

	public void setP(java.lang.Boolean p) {
		this.p = p;
	}

	public P(java.lang.Boolean p) {
		this.p = p;
	}

}